<?php

namespace App\Traits;

use App\Services\KoskidexClient;

trait Searchable
{
    /**
     * Listen for Eloquent model lifecycle events.
     * Keeps Koskidex synchronized on every MySQL/Postgres record save.
     */
    public static function bootSearchable()
    {
        static::saved(function ($model) {
            $model->syncToKoskidex();
        });

        static::deleted(function ($model) {
            $model->removeFromKoskidex();
        });
    }

    /**
     * Remove from Koskidex
     */
    public function removeFromKoskidex()
    {
        $config = $this->getKoskidexConfig();
        if (!$config) return;

        /** @var KoskidexClient $client */
        $client = app(KoskidexClient::class);
        $client->deleteDocument($config['index_name'], (string) $this->getKey());
    }

    /**
     * Get the specific index configuration from the koskidex.php configuration file
     */
    public function getKoskidexConfig()
    {
        return config('koskidex.indices.' . static::class);
    }

    /**
     * Transform the model into a formatted array mapping ONLY the fields 
     * configured in searchable_fields. Automatically handles null values.
     */
    public function toSearchableArray()
    {
        $config = $this->getKoskidexConfig();
        if (!$config) {
            return $this->toArray();
        }

        $fields = $config['searchable_fields'] ?? [];
        $data = ['id' => (string) $this->getKey()];

        foreach ($fields as $field) {
            $data[$field] = $this->{$field};
        }

        return $data;
    }

    /**
     * Sync push to Koskidex
     */
    public function syncToKoskidex()
    {
        $config = $this->getKoskidexConfig();
        if (!$config) return;

        /** @var KoskidexClient $client */
        $client = app(KoskidexClient::class);
        $client->addDocuments($config['index_name'], [$this->toSearchableArray()]);
    }

    /**
     * Allows searching directly using the Laravel Model
     * e.g. User::koskidexSearch('Mario');
     */
    public static function koskidexSearch($query, $options = [])
    {
        $config = config('koskidex.indices.' . static::class);
        if (!$config) return collect();

        /** @var KoskidexClient $client */
        $client = app(KoskidexClient::class);
        $response = $client->search($config['index_name'], $query);

        $hits = collect($response['hits'] ?? []);
        
        // EXAMPLE OF CUSTOM HIT THRESHOLD LOGIC
        // If in the future we modify the Golang engine to provide a score limit
        // in the API, we can pass it there. Otherwise, we filter the cache here in PHP.
        // $threshold = $options['hit_threshold'] ?? ($config['hit_threshold'] ?? 0);

        // Extracts the IDs returned from the search (e.g. [1, 5, 23])
        $ids = $hits->pluck('id');

        // Load the actual Eloquent Models from the MySQL DB using a whereIn
        $models = static::whereIn((new static)->getKeyName(), $ids)->get()->keyBy((new static)->getKeyName());

        // Remap the results strictly keeping the sorting order generated by the Koskidex ranker
        return $hits->map(function ($hit) use ($models) {
            return $models->get($hit['id']);
        })->filter()->values();
    }
}
